name: flutter_downloader
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  creator: ^0.3.2
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  html: ^0.15.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
