name: flutter_downloader
description: GUI to download youtube video from url using yt-dlp.exe behind the scenes.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  creator: ^0.3.2
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  html: ^0.15.2
  http: ^1.1.0
  riverpod: ^2.4.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

assets:
  - assets/

flutter_launcher_icons:
  image_path: assets/Test.ico
  windows:
    generate: true
    image_path: assets/Test.ico
    icon_size: 48